# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  workflow_dispatch:
    inputs:
      v:
        description: 'Version'
        required: true
        type: string
  

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release
      
    - name: Pakage
      run: > 
        dotnet pack --no-restore --no-build --configuration Release -p:PackageVersion=${{ inputs.v }} --output .
        
    - name: Publish
      run: >
        dotnet nuget push PackageUtils.${{ inputs.v }}.nupkg 
        -s https://nuget.pkg.github.com/alihagh1383/index.json 
        -k ${{ secrets.NUGET_AUTH_TOKEN }}
